### ISSUE TITLE
Use seedfiles/manifests as inputs to launch pipelines

### ISSUE THREAD

**Issue by sunitj** [FischbachLab/nf-binqc#1]
**Context**
Currently the pipeline is launched by pointing it to a directory with the fasta files. The issue is that once the pipeline is complete, there is no way to track which input genome was used to produce this output.

A seedfile/manifest file will make the pipeline launch consistent with other pipelines and provide a degree of provenance.

**Comment by xmeng** [comment]
Added a —seedfile option to allow user to specify a genome name and its path in a csv file
Resolved issue #1
