### ISSUE TITLE
Add report generation as part of the pipeline

### ISSUE THREAD

**Issue by sunitj** [FischbachLab/nf-binqc#2]
**Context**

Once the pipeline has completed, users often download the results to their local machines and run a python script for aggregation. Since there is no manual intervention required, this process can be include into the pipeline, thus saving the final report along the run. 

This report can further be aggregated into a database within AWS (using Glue/Athena) for easier access and comparison.

Also, update report output to include the pipeline version and assembly s3path.

**Comment by xmeng** [comment]
The report generation was added to the pipeline.
